In [2]:
import numpy as np

In [3]:
np

<module 'numpy' from 'c:\\anaconda\\lib\\site-packages\\numpy\\__init__.py'>

## Creating arrays

In [6]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [10]:
a=np.array([1,2,3,5,7,12])
a

array([ 1,  2,  3,  5,  7, 12])

In [12]:
a[2] = 10

In [13]:
a

array([ 1,  2, 10,  5,  7, 12])

In [16]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [20]:
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

## Multi-dementional arrays

In [21]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [24]:
n=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [27]:
n[0,1] = 20

In [28]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [31]:
n[2]

array([7, 8, 9])

In [32]:
n[2]=[1,1,1]

In [33]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [35]:
n[:,2]

array([3, 6, 1])

In [36]:
n[:]

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [37]:
n[:,2]=[0,1,2]

In [38]:
n

array([[ 1, 20,  0],
       [ 4,  5,  1],
       [ 1,  1,  2]])

## Ramdomly generated arrays

In [51]:
np.random.seed(2)
100 * np.random.rand(5, 2)

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [52]:
np.random.seed(2)
np.random.randn(5, 2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [53]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5, 2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

## Element-wise operations

In [54]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [56]:
a + 1

array([1, 2, 3, 4, 5])

In [58]:
a * 2

array([0, 2, 4, 6, 8])

In [66]:
b = (10  + a * 2) **2 / 100

In [70]:
a / b + 10

array([10.        , 10.69444444, 11.02040816, 11.171875  , 11.2345679 ])

## Comparison operations

In [71]:
a >= 2

array([False, False,  True,  True,  True])

In [73]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [72]:
a > b

array([False, False,  True,  True,  True])

In [74]:
a[a>b]

array([2, 3, 4])

## Summarizing operations

In [76]:
a

array([0, 1, 2, 3, 4])

In [77]:
a.min()

0

In [78]:
a.max()

4

In [79]:
a.sum()

10

In [80]:
a.mean()

2.0

In [81]:
a.std()

1.4142135623730951

In [82]:
n.sum()

35

In [83]:
n

array([[ 1, 20,  0],
       [ 4,  5,  1],
       [ 1,  1,  2]])